### ISSUE TITLE
Program icons

### ISSUE THREAD

**Issue by mrcanelas** [freearhey/epg-grabber#1]
Hey man, your work is incredible, but I have a doubt, is it possible or will it be possible in the future to add the program icons? I'm using it on Android TV and to be perfect, the program icons are just missing.

**Comment by freearhey** [comment]
You are right, it's not possible to do that at the moment, but I will try to fix it soon.

**Comment by freearhey** [comment]
Done.

**Comment by mrcanelas** [comment]
Thank you very much man, it was great, but I have a doubt, my programs are delayed by 3 hours, I think it has something to do with my time zone (UTC -3), how do you configure this?

**Comment by freearhey** [comment]
I'm currently using the [utc](https://day.js.org/docs/en/plugin/utc) plugin for dayjs to parse the date.
