### ISSUE TITLE
Any way to combine multiple output files?

### ISSUE THREAD

**Issue by PopeyeTheSai10r** [freearhey/epg-grabber#10]
Hello, I love the program and what it is capable of doing.
I was looking for a way to combine multiple outputs to create one EPG around a playlist.

Is this something that's possible with the latest version?
If not available at the moment, Is that something that could be added with later releases?

**Comment by freearhey** [comment]
One option is to parse the output files, collect them into one list and then generate a new EPG. This can be done with a tool like [node-xmltv](https://github.com/nice-shot/node-xmltv).

Another option is to use epg-grabber as a js module like it is done [here](https://github.com/freearhey/epg-grabber/blob/master/bin/epg-grabber.js). That way you can generate the output you want right away.

**Comment by PopeyeTheSai10r** [comment]
Perfect. Thank you!
