### ISSUE TITLE
mileseconds vs milliseconds

### ISSUE THREAD

**Issue by benbelgium** [freearhey/epg-grabber#11]
Hi Guys

Great software! Small remark:

Usage: epg-grabber [options]
Node.js CLI tool for grabbing EPG from different sites
Options:
  -v, --version           output the version number
  -c, --config <config>   Path to [site].config.js file
  -o, --output <output>   Path to output file
  --channels <channels>   Path to channels.xml file
  --lang <lang>           Set default language for all programs
  --days <days>           Number of days for which to grab the program
  --delay <delay>         Delay between requests (in **mileseconds**)
  --timeout <timeout>     Set a timeout for each request (in **mileseconds**)
  --cache-ttl <cacheTtl>  Maximum time for storing each request (in milliseconds)
  --gzip                  Compress the output (default: false)
  --debug                 Enable debug mode (default: false)
  --curl                  Display request as CURL (default: false)
  --log <log>             Path to log file
  --log-level <level>     Set log level (default: "info")
  -h, --help              display help for command

**Comment by freearhey** [comment]
Fixed in `v0.29.8`.
