### ISSUE TITLE
Multiple channel white same request

### ISSUE THREAD

**Issue by sensodejay** [freearhey/epg-grabber#16]
Hello

I played white some epg grabbers for different devices.
There is noticed some of the grabbers allow to get data from multiple channel at same time approximate between 4 to 10 channels per request depending on the site. This is often done by separate the side_id by a comma.

But also means the parser is able to handle the channels.

Quest is can you grabber provide this option or can be implemented. This will speed up the process in future.

**Comment by freearhey** [comment]
This feature was added in `v0.31.0`. 

You can specify the maximum number of concurrent requests either via the `--max-connections` argument on the command line or via the `maxConnections` property in the site config.
