### ISSUE TITLE
The "stop" attribute of the programme element shouldn't be required

### ISSUE THREAD

**Issue by ItsKlork** [freearhey/epg-grabber#17]
In this library the `stop` attribute is required (Or at least the README claims it is) but the XMLTV format [doesn't require](https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd#L308) it.

**Comment by freearhey** [comment]
The attribute `stop` is required.

**Comment by ItsKlork** [comment]
The XMLTV format states that it isn't required and that it is an implied attribute based on the next start time. Read the link I sent in the original comment.
