### ISSUE TITLE
Add LCN in channel tag

### ISSUE THREAD

**Issue by GreenSnakeLinux** [freearhey/epg-grabber#19]
Hello,

It will be really use full to add the optional LCN property in channel tag record:
LCN: Logical Channel Number
https://en.wikipedia.org/wiki/Virtual_channel
It will help to sort the channels by this number in applications.
Most of users prefer to see the channels list by channel number.
(I know that for some countries this number can be different by state, but in Europe it's fix by country)
Thanks

**Comment by freearhey** [comment]
Added in [v0.37.0](https://github.com/freearhey/epg-grabber/releases/tag/v0.37.0)
