### ISSUE TITLE
Async functions

### ISSUE THREAD

**Issue by mrcanelas** [freearhey/epg-grabber#2]
Is it possible to do asynchronous functions? for example, make an each, search for a url, wait to make a request on that url and scratch data and return with the function, is it possible to do this?

**Comment by freearhey** [comment]
I don't know, but I'll try to look into it when I have some free time.

**Comment by mrcanelas** [comment]
Hey man all right, I had left this project a bit of a lake but now I'm back with it, from what I understand `epg-grabber` doesn't work with asyncronous functions, I want to increase the size of my tab to about three days, but my api only provides one day per request so i have to make three requests and merge their data, can you help me with that?

`async function getMoreDays(channel) {
  const dates = [
    `https://contentapi-br.cdn.telefonica.com/25/default/pt-BR/schedules?ca_deviceTypes=null%7C401&fields=Title,Description,Start,End,EpgSerieId,SeriesPid,SeasonPid,images.videoFrame,images.banner&orderBy=START_TIME:a&filteravailability=false&starttime=${getTimestamp(yesterday)}&endtime=${getTimestamp(today)}&livechannelpids=${channel}`,
    `https://contentapi-br.cdn.telefonica.com/25/default/pt-BR/schedules?ca_deviceTypes=null%7C401&fields=Title,Description,Start,End,EpgSerieId,SeriesPid,SeasonPid,images.videoFrame,images.banner&orderBy=START_TIME:a&filteravailability=false&starttime=${getTimestamp(today)}&endtime=${getTimestamp(tomorrow)}&livechannelpids=${channel}`,
    `https://contentapi-br.cdn.telefonica.com/25/default/pt-BR/schedules?ca_deviceTypes=null%7C401&fields=Title,Description,Start,End,EpgSerieId,SeriesPid,SeasonPid,images.videoFrame,images.banner&orderBy=START_TIME:a&filteravailability=false&starttime=${getTimestamp(tomorrow)}&endtime=${getTimestamp(afterTomorrow)}&livechannelpids=${channel}`,
  ]
  const data = await Promise.all(dates.map(async (elem) => {
    const content = await axios.get(elem)
    return content.data.Content
  }))
  const items = [].concat(...data)
  return items
}

parser: function ({channel}) {
      const items = await getMoreDays(channel.site_id)
      const programs = items.map(item => {
        const title = (item.Title.split(':')[1] != undefined) ? item.Title.split(':')[0] : item.Title
        const category = (item.Title.split(':')[1] != undefined) ? item.Title.split(':')[1] : ''
        const start = (dayjs.unix(item.Start).get('h') < 3) ? dayjs.unix(item.Start).add(1, 'd') : dayjs.unix(item.Start)
        const stop = (dayjs.unix(item.End).get('h') < 3) ? dayjs.unix(item.End).add(1, 'd') : dayjs.unix(item.End)
        const icon = item.Images.VideoFrame[0].Url
        return {
          title,
          category,
          description: item.Description,
          start: start,
          stop: stop,
          icon
        }
      })
      return programs
  },`

**Comment by freearhey** [comment]
You can do the same by passing the desired number of days as a parameter:

**example.com.config.js**
```js
module.exports = {
  site: 'example.com',
  channels: 'example.com.channels.xml',
  days: 3,
  url: function({ channel, date }) {
    return `http://example.com/${date.format('YYYYMMDD')}/${channel.site_id}.json`
  },
  parser: ({ content }) {
    // parse
  }
}
```

In this case the parser will run three times with three different dates.

**Comment by mrcanelas** [comment]
For min it didn't work, I need to send two dates in unix format to my API, I put the number of days, but it seems that it doesn't add more days to the request.

```js
const today = dayjs.utc()
const tomorrow = dayjs(today).add(1, 'd')
const starttime = dayjs(today).unix()
const endtime = dayjs(tomorrow).unix()

module.exports = {
  lang: 'pt',
  site: 'vivoplay.com.br',
  channels: 'vivoplay.com.br.channels.xml',
  days: 3,
  output: '.gh-pages/guide.xml',

  request: {

    method: 'GET',
    headers: {
      'Content-Type':
        'application/json; charset=utf-8',
    },
  },

  url: function ({channel}) {
    return `https://contentapi-br.cdn.telefonica.com/25/default/pt-BR/schedules?ca_deviceTypes=null%7C401&fields=Title,Description,Start,End,EpgSerieId,SeriesPid,SeasonPid,images.videoFrame,images.banner&orderBy=START_TIME:a&filteravailability=false&starttime=${starttime}&endtime=${endtime}&livechannelpids=${channel.site_id}`;
  },```

Console: 
```
Loading 'sites\vivoplay.com.br.channels.xml'...
Parsing:
  vivoplay.com.br - A&E - Aug 21, 2021 (27 programs)
  vivoplay.com.br - A&E - Aug 22, 2021 (27 programs)
  vivoplay.com.br - A&E - Aug 23, 2021 (27 programs)
  vivoplay.com.br - Agro+ - Aug 21, 2021 (41 programs)
  vivoplay.com.br - Agro+ - Aug 22, 2021 (41 programs)
  vivoplay.com.br - Agro+ - Aug 23, 2021 (41 programs)
File '.gh-pages/guide.xml' successfully saved
Finish
```
