### ISSUE TITLE
error grabbing osn.com

### ISSUE THREAD

**Issue by yarafie** [freearhey/epg-grabber#6]
getting the below error on several channels grabbing osn.com epg from the iptv-org osn.com
anything specific I need to do?

......
[11/196] osn.com - AlMamlakaTV.jo - Nov 21, 2021 (0 programs)
  Error: Unexpected token < in JSON at position 0
.......

**Comment by freearhey** [comment]
Here is an example of a working config for this site: https://github.com/iptv-org/epg/blob/master/sites/osn.com/osn.com.config.js
