### ISSUE TITLE
mncvision.id

### ISSUE THREAD

**Issue by kyliezero** [freearhey/epg-grabber#7]
I use a script from here [iptv-org](https://github.com/iptv-org/epg/tree/master/sites/mncvision.id)  which only takes data from page one, so how do I get the data from the second page and so on?

![IMG_20220407_075221](https://user-images.githubusercontent.com/87708571/162098608-637e3b45-80bb-441b-b2a0-68001901c54d.jpg)
![IMG_20220407_074909](https://user-images.githubusercontent.com/87708571/162098619-35b3fe48-8b2c-48b5-8f32-da248c2507e4.jpg)
![IMG_20220407_074928](https://user-images.githubusercontent.com/87708571/162098624-3303b7fb-660e-4626-8107-ad2e8fc94249.jpg)

**Comment by lynxnexy** [comment]
I'm here trying to retrieve data for 3 days, 7-9... on the 7th all data from page 1-3 is taken, while on 8-9 only page 1 data is taken, can you fix this script [iptv-org](https://github.com/iptv-org/epg/tree/master/sites/mncvision.id) , thank you very much

**Comment by kyliezero** [comment]
> I'm here trying to retrieve data for 3 days, 7-9... on the 7th all data from page 1-3 is taken, while on 8-9 only page 1 data is taken, can you fix this script [iptv-org](https://github.com/iptv-org/epg/tree/master/sites/mncvision.id) , thank you very much

we have the same problem

**Comment by freearhey** [comment]
Closed in favor https://github.com/iptv-org/epg/issues/523
